remote_theme: elrayle/documentation-theme-jekyll@gh-pages

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: false
      sidebar: home_sidebar
      
sidebars:
- home_sidebar
